image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/2.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose -f /home/appveyor/projects/diploma/docker-compose.yml up -d
  - sleep 20
  - java -jar ./artifacts/aqa-shop/aqa-shop.jar --spring.datasource.url=jdbc:mysql://localhost:3306/app &
  - sleep 20

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3306/app
  - sudo docker-compose down